# Generated by Django 5.0.6 on 2024-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter_and_batter_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('cake_size', models.CharField(max_length=255)),
                ('cake_flavour', models.CharField(max_length=255)),
                ('frosting', models.CharField(max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('decorations', models.CharField(blank=True, max_length=255, null=True)),
                ('special_messages', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('special_considerations', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
