# Generated by Django 5.0.6 on 2024-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter_and_batter_backend_app', '0002_customcakeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
